### ISSUE TITLE
Define rq-scheduler version in the dependency 

### ISSUE THREAD

**Issue by Cortezz** [rq/Flask-RQ2#49] opened 2018-02-12 17:36 UTC
There is no defined `rq-scheduler` version in the dependency list. As such, it fetches the latest version. 

As it stands, the latest version of `rq-scheduler` (0.8.1) is not compatible with`Flask-RQ2`

Here is the error:
```
Traceback (most recent call last):
  File "manage.py", line 60, in <module>
    manager.run()
  File "/Users/joaocosta/.virtualenvs/chat-api/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/Users/joaocosta/.virtualenvs/chat-api/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/Users/joaocosta/.virtualenvs/chat-api/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 23, in scheduler
    scheduler = rq.get_scheduler()
  File "/Users/joaocosta/.virtualenvs/chat-api/lib/python2.7/site-packages/flask_rq2/app.py", line 288, in get_scheduler
    raise RuntimeError('Cannot import rq-scheduler. Is it installed?')
RuntimeError: Cannot import rq-scheduler. Is it installed?
```

I don't know what is the latest version of `rq-scheduler` that works but 0.7.0 is compatible.

**Comment by Cortezz** [comment] 2018-02-12 17:38
@joaofcosta also reported this.

**Comment by jezdez** [comment] 2018-03-02 11:26
I can't reproduce this locally, which makes me wonder if you're running the latest version. Please provide more info how to reproduce this.

**Comment by jezdez** [comment] 2018-03-02 20:18
Closing as the original request that rq-scheduler should be defined with a version has been fixed since https://github.com/rq/Flask-RQ2/commit/d4d5e526d0790d1968f34b10ec42a12ab6e944cd#diff-2eeaed663bd0d25b7e608891384b7298R61.

**Closed by jezdez** 2018-03-02 20:18 UTC
